version: "3.9"
services:
  latest:
    image: mindex-java-challenge:1.0.0
    expose:
      - 8080
    ports:
    - "8080:8080"
    build: 
      context: .
      args:
        JAR_FILE: mindex-java-code-challenge-0.0.1-SNAPSHOT.jar